### ISSUE TITLE
Capture use cases for tagging

### ISSUE THREAD

**Issue by auxesis** [flapjack/flapjack#676]
Some initially captured used cases: 

 - Rollup
 - Multi-tenancy
 - Gateways
 - Web interface
 - API querying (e.g. get a list of all entities that have active checks, i.e. not disabled, would query /checks endpoint with tags + disabled parameter)

Once we capture these use cases for tagging, we must:

 - [x] Define what the scope of the tagging changes will be to Flapjack
 - [ ] Define internal and external policy around tagging (e.g. `entity:` namespace is reserved)
 - [ ] Implement tagging changes

**Comment by jessereynolds** [comment]
What's left as action items from this issue? I'd like to create separate issues for what's remaining and close this one as it's a bit wooly. 

[ ] @ali-graham to document how the notification rule data model works in 2.x

Anything else coming out of this issue that still needs addressing?

**Comment by ali-graham** [comment]
(I'll just note that the data model described above has been simplified somewhat, and certain of those details are non-public, i.e. not intended to be exposed via the API, any CLI interfaces, etc.)

We should probably also write a migration document telling people what will happen to their old data when upgrading (and, by extension, telling people how to model their setups using tags instead of entities).

**Comment by jessereynolds** [comment]
Tag based rollup issue created earlier: https://github.com/flapjack/flapjack/issues/833

**Comment by jessereynolds** [comment]
Going to mark this closed, I think we've now got separate issues open for the pertinent outstanding actions.
