### ISSUE TITLE
unable update of timezone

### ISSUE THREAD

**Issue by pulecp** [flapjack/flapjack#771]
Hi,
I tried to update a timezone of contact over curl and diner. Return code is OK but the timezone has not changed.

    [root@flapjack ~]# uname -a
    Linux flapjack.internal.inuits.eu 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
    [root@flapjack ~]# gem list|grep flapjack
    flapjack-diner (1.2.0)
    flapjack-syrup (0.6)
    [root@flapjack ~]# yum list installed|grep flap   
    flapjack.x86_64         1.2.0_0.20141107131800-1.el6

**Comment by jessereynolds** [comment]
Hi @pulecp 

Apologies for the delayed response! 

It's possible you encountered this bug - https://github.com/flapjack/flapjack/issues/791 - which was fixed in 1.4.0. Could you try the latest 1.x version and see if you still have problems? If you do, please re-open this issue and include an example API request. 

Thank you

**Comment by pulecp** [comment]
Hi @jessereynolds,

sorry but I don't work with flapjack anymore.

**Comment by jessereynolds** [comment]
@pulecp no worries
