### ISSUE TITLE
JSONAPI v1.0 compliance

### ISSUE THREAD

**Issue by ghost** [flapjack/flapjack#800]
After numerous changes to the spec, it looks like JSONAPI is finally converging on a release version (e.g. https://github.com/json-api/json-api/pull/341 ). When I start this issue, I'll build a task list of differences between the spec and our current behaviour, and cross those off as I go.

The aim after JSONAPI v1 is to preserve backwards compatibility throughout that major release version, so that should reduce the flux for Flapjack's API part once this is in place.

**Comment by jessereynolds** [comment]
:+1:

**Comment by ali-graham** [comment]
- [ ] `data`/`meta`/`linked` wrapping at JSON root
- [ ] `type` field in all resource blocks where needed
- [ ] URLs for self and resource for all associations
- [ ] data in `linked` block for all `include` operations, referenced by full-syntax association block with ids
- [ ] revise top level `links` block to new details (`self` URL and pagination URLs if required)
- [ ] revise sparse fieldset support to apply to associations as well
- [ ] revise sorting to require that each field have `+` or `-` at the start, to show order
- [ ] check that pagination support still complies with the new details
- [ ] remove search endpoint, support filter parameter on the data types and attributes that supported
- [ ] revise POST, PUT to require `data` wrapping at JSON root and `type` member
- [ ] ensure 403 is sent if POST fails due to invalid submitted `id`
- [ ] ensure 409 is sent on POST if `id` exists or the `type` doesn't match the endpoint
- [ ] ensure `self` key in returned data from POST matches `Location` header
- [ ] revise `PUT` with relationship data to use the new `links` data structures; ensure that failure applies no changes
- [ ] revise relationship changes via `:resource_name/:id/links/:assoc` URLs to use new data structure
- [ ] check that error structures are still conformant
- [ ] All of the above tested & working for all end points

**Comment by jessereynolds** [comment]
So close

![screenshot 2015-04-17 16 00 54](https://cloud.githubusercontent.com/assets/391439/7197035/00491ba0-e51b-11e4-9f57-413503182145.png)

**Comment by ali-graham** [comment]
The last three are just validation tasks, I just need to take the time to check that it's doing what it should :)

**Comment by ali-graham** [comment]
Calling this done.

**Comment by jessereynolds** [comment]
Party! :tada:
