### ISSUE TITLE
Inconsistency: Flapjack::Data::Check.end_scheduled_maintenance vs Flapjack::Data::Check.clear_unscheduled_maintenance

### ISSUE THREAD

**Issue by Hobbsee** [flapjack/flapjack#814]
It looks like we've renamed end_unscheduled_maintenance to clear_unscheduled_maintenance in master, but haven't renamed the corresponding scheduled maintenance check.  Is this intentional?

I'm also unclear at what each of the parameters here is supposed to be.  Is the latter parameter on both the time that you want the maintenance to end?

**Comment by jessereynolds** [comment]
All good questions. @ali-graham can you shed any light?

**Comment by ali-graham** [comment]
There's only ever one extant unscheduled maintenance period per check, and it can't be deleted per se. If you end it it is removed from the current scope, thus "cleared".

For scheduled maintenance periods, they can be "cleared" (if currently running) or "deleted" (if they haven't happened yet). 'End' is used as a verb encompassing both scenarios.

If this isn't clear I'm open to renaming things, but want to keep the distinctions above.

**Comment by ali-graham** [comment]
Also, the `at_time`/`end_time` parameters are the times you want the maintenance period to end. Because there can only be one unscheduled maintenance period for the check, `clear_unscheduled_maintenance` doesn't take an unscheduled maintenance period object as a parameter, while `end_scheduled_maintenance` does take a scheduled maintenance period object as a parameter.

The data model associations for these are a bit clunky as they're backed by two redis sorted sets each, to be able to query on start and end times; some more syntactical sugar overlying this would be good, especially if it can be folded down into `zermelo`.

**Comment by jessereynolds** [comment]
Sounds fair to me. Convinced, @Hobbsee ?

**Comment by Hobbsee** [comment]
Yep, that's fine.
