### ISSUE TITLE
sns gateway failing with RequestExpired

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#878]
Pulled out of [this comment](https://github.com/flapjack/flapjack/pull/868#issuecomment-112239425) by  @mholtrlc :

Still having an issue after building and installing the 1.6rc3 package. Now I am receiving this error:

2015-06-15T16:48:06.700226-07:00 [DEBUG] :: flapjack-sns :: server response: 

Sender
RequestExpired
Request has expired. Timestamp date: 2015-06-15T16:48:05Z

ab1b850e-efcc-53e0-985d-c8f789b07f4c

**Comment by jessereynolds** [comment]
It looks like the request timestamp is being set to UTC without a corresponding time change (ie the -07:00 is being set to Z while the time stays the same). Or something ...

**Comment by ali-graham** [comment]
Should be fixed by 76b3474e923567cbaa97ff106c3c96f7c5cdb5ac , sorry :( Think I must have thought the `Z` was a `%Z` or something.

**Comment by mholtrlc** [comment]
and now we are back to 

````
2015-06-15T22:20:13.621740-07:00 [DEBUG] :: flapjack-sns :: server response: <ErrorResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>
  </Error>
  <RequestId>dc4d5a73-587f-57f5-be92-178aec32ffe7</RequestId>
</ErrorResponse>
````

**Comment by ali-graham** [comment]
Hmm, the tests pass locally but fail on Travis as well due to the signature being different. This possibly points to environmental differences?

**Comment by mholtrlc** [comment]
hmmm not sure, i'm not sure... I've been playing with it all evening and haven't gotten it to work on my machine

**Comment by jessereynolds** [comment]
Travis failure on Ruby 2.2.2 says:

```
     Failure/Error: aws_sns.deliver(alert)
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: POST http://sns.us-east-1.amazonaws.com/?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Action=Publish&Message=Recovery:%20'ping'%20on%20example.com%20is%20OK%20at%2031%20Oct%2013:45,%20smile&Signature=gxoUQ8qUYBQbqgf3XmbiSPZ8qTJZ9WyC81EKc67FY0g=&SignatureMethod=HmacSHA256&SignatureVersion=2&Subject=Recovery:%20'ping'%20on%20example.com%20is%20OK&Timestamp=2013-10-31T13:45:00Z&TopicArn=arn:aws:sns:us-east-1:698519295917:My-Topic
```

**Comment by mholtrlc** [comment]
my thought is you have your travis set up not to allow external url calls during the testing and even if you did it would fail due to the fake Access Keys you have coded as a fallback?

**Comment by ali-graham** [comment]
It's supposed to stub the correct args (and thus not do the web request), but the signature is the only argument that is different. This test has behaved the same way for me in multiple timezones (in Australia and also in the US) -- am I missing something about the way SHA256 is calculated that would mean that the same operation carried out on someone else's machine would give different results?

**Comment by mholtrlc** [comment]
I'm honestly not sure, this is the first time i've ever worked with Amazon SNS so I don't know all the particulars beyond googling and trying different things.... been working on it all evening haha

**Comment by ali-graham** [comment]
Nope, even then it expects a different signature than the one that gets generated here :/ Not sure.

**Comment by mholtrlc** [comment]
yea... it's weird cause it's generating a proper signature but it's expired... once you start playing with the converting the time to UTC it goes back to not matching.... played with it for several hours today

**Comment by ali-graham** [comment]
Ah, so it seems to be getting the signature right without that? I might look at the SNS docs some more, I used the time zone code as is as it's what the official SDK is doing but I must have missed some detail.

**Comment by mholtrlc** [comment]
Yea it does... At least I'm assuming so since it comes back with request
expired when the time isn't converted to utc instead of saying The
signature doesn't match

On Tuesday, June 16, 2015, Ali Graham <notifications@github.com> wrote:

> Ah, so it seems to be getting the signature right without that? I might
> look at the SNS docs some more, I used the time zone code as is as it's
> what the official SDK is doing but I must have missed some detail.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flapjack/flapjack/issues/878#issuecomment-112421196>.
>


-- 

[image: Real Life Church] <http://www.reallifechurch.org>

Michael Holt / IT Administrator
(661) 705-4711/ mholt@reallifechurch.org

Real Life Church Office: (661) 775-7401
23841 Newhall Ranch Rd
Valencia, CA 91355
http://www.reallifechurch.org

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by ali-graham** [comment]
Closing as the timestamp stuff is fixed in `maint/1.x` now; we'll keep looking into the signature issues.
