### ISSUE TITLE
Are the acknowledgements sent to Nagios?

### ISSUE THREAD

**Issue by brunoqc** [flapjack/flapjack#912]
I saw on http://flapjack.io/docs/1.0/usage/Architecture/ that XMPP and pagerduty handle acknowledgements but I'm wondering if the acknowledgements are sent to Nagios.

I'm under the impression they are not since the link is not 2-way on the architecture graph and I was wondering if there was a reason why.

**Comment by jessereynolds** [comment]
That's correct. The two methods for connecting Nagios to Flapjack (that I'm aware of) consist of just receiving the results of every check execution performed by Nagios. 

The reason is that Flapjack replaces the notification features of Nagios and as such there's no need for Nagios to know if a human acknowledges a failing check.
